@startuml
!include .\\Lab01\Program.puml
!include .\\Lab02\Product.puml
!include .\\Lab02\Program.puml
!include .\\Lab02\Student.puml
!include .\\Lab03\GlobalVar.puml
!include .\\Lab03\Program.puml
!include .\\Lab04\Context.puml
!include .\\Lab04\Program.puml
!include .\\Lab01\CalculationTwoNumMenuItems\Division.puml
!include .\\Lab01\CalculationTwoNumMenuItems\Sum.puml
!include .\\Lab01\Interface\CalculationTwoNumMenuItem.puml
!include .\\Lab01\Interface\MainMenuItem.puml
!include .\\Lab01\Interface\MenuItem.puml
!include .\\Lab01\MainMenuItems\00000Exit.puml
!include .\\Lab01\MainMenuItems\AverageTwoNumber.puml
!include .\\Lab01\MainMenuItems\CalculationTwoNum.puml
!include .\\Lab01\MainMenuItems\Fibonacci.puml
!include .\\Lab01\MainMenuItems\PerfectSquare.puml
!include .\\Lab01\MainMenuItems\Square.puml
!include .\\Lab01\Public\InvalidOption.puml
!include .\\Lab01\Public\MenuDict.puml
!include .\\Lab01\Public\Option.puml
!include .\\Lab01\Public\PrintMenu.puml
!include .\\Lab02\Interface\IUpdateProduct.puml
!include .\\Lab02\Interface\MainMenuItem.puml
!include .\\Lab02\Interface\MenuItem.puml
!include .\\Lab02\Interface\SearchProducts.puml
!include .\\Lab02\MainMenuItems\00000Exit.puml
!include .\\Lab02\MainMenuItems\AddProduct.puml
!include .\\Lab02\MainMenuItems\PrintProductInfo.puml
!include .\\Lab02\MainMenuItems\SearchProduct.puml
!include .\\Lab02\MainMenuItems\Sort.puml
!include .\\Lab02\MainMenuItems\UpdateProduct.puml
!include .\\Lab02\Public\0001Back.puml
!include .\\Lab02\Public\InvalidOption.puml
!include .\\Lab02\Public\MenuDict.puml
!include .\\Lab02\Public\Option.puml
!include .\\Lab02\Public\PrintMenu.puml
!include .\\Lab02\SearchProductsItems\ByName.puml
!include .\\Lab02\SearchProductsItems\ByPrice.puml
!include .\\Lab02\SearchProductsItems\ByProductionDate.puml
!include .\\Lab02\UpdateProductItems\ByName.puml
!include .\\Lab02\UpdateProductItems\ByPrice.puml
!include .\\Lab03\Interface\CalculationTwoNumMenuItem.puml
!include .\\Lab03\Interface\MainMenuItem.puml
!include .\\Lab03\Interface\MenuItem.puml
!include .\\Lab03\Interface\SearchStudentMenuItem.puml
!include .\\Lab03\Interface\SubMenuItem.puml
!include .\\Lab03\Menu\00000Exit.puml
!include .\\Lab03\Menu\CreateStudent.puml
!include .\\Lab03\Menu\DeleteStudent.puml
!include .\\Lab03\Menu\SearchStudent.puml
!include .\\Lab03\Menu\ShowStudents.puml
!include .\\Lab03\Models\Person.puml
!include .\\Lab03\Models\Student.puml
!include .\\Lab03\Public\0001Back.puml
!include .\\Lab03\Public\InvalidOption.puml
!include .\\Lab03\Public\MenuDict.puml
!include .\\Lab03\Public\Option.puml
!include .\\Lab03\Public\PrintMenu.puml
!include .\\Lab04\Interface\IMenuItem.puml
!include .\\Lab04\Model\Product.puml
!include .\\Lab04\Singleton\ProductDict.puml
!include .\\Lab04\Singleton\ProductIDCount.puml
!include .\\Lab04\MenuItem\MainMenu\AddProduct.puml
!include .\\Lab04\MenuItem\MainMenu\Exit.puml
!include .\\Lab04\MenuItem\MainMenu\ShowAllProduct.puml
!include .\\Lab01\obj\Debug\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\Lab01\obj\Debug\net7.0\Lab01.AssemblyInfo.puml
!include .\\Lab01\obj\Debug\net7.0\Lab01.GlobalUsings.g.puml
!include .\\Lab02\obj\Debug\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\Lab02\obj\Debug\net7.0\Lab02.AssemblyInfo.puml
!include .\\Lab02\obj\Debug\net7.0\Lab02.GlobalUsings.g.puml
!include .\\Lab03\Menu\SubMenu\SearchStudentMenuItems\ById.puml
!include .\\Lab03\Menu\SubMenu\SearchStudentMenuItems\ByName.puml
!include .\\Lab03\obj\Debug\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\Lab03\obj\Debug\net7.0\Lab03.AssemblyInfo.puml
!include .\\Lab03\obj\Debug\net7.0\Lab03.GlobalUsings.g.puml
!include .\\Lab04\obj\Debug\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\Lab04\obj\Debug\net7.0\Lab04.AssemblyInfo.puml
!include .\\Lab04\obj\Debug\net7.0\Lab04.GlobalUsings.g.puml
@enduml
